# Generated by Django 4.1.6 on 2023-03-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='Имя не присвоено', max_length=128)),
                ('category_picture', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование товара')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(max_length=20, verbose_name='Размер')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.category')),
            ],
        ),
    ]
